#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/LogFunctions  # Tutorial log-file functions
#------------------------------------------------------------------------------
# change to run folder 
cd run
# remove the Mesh folder 
rm -r mesh

echo mesh folder removed
#------------------------------------------------------------------------------