#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/LogFunctions  # Tutorial log-file functions
#------------------------------------------------------------------------------

# remove the output folder 
rm -r output

echo output folder removed

#------------------------------------------------------------------------------
