#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/bin/tools/LogFunctions  # Tutorial log-file functions
#------------------------------------------------------------------------------
# change to output folder 
cd output
# remove the ResultTransient folder 
rm -r resultTransient

echo resultTransient folder removed
#------------------------------------------------------------------------------